# GoReleaser 配置文件
# 用于本地构建和发布可执行文件
# 安装: https://goreleaser.com/install/
# 使用: goreleaser release --snapshot --skip-publish --rm-dist

version: 1

project_name: cos-uploader

builds:
  - id: default
    binary: cos-uploader
    main: .
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    env:
      - CGO_ENABLED=0

    # 针对特定平台的构建选项
    overrides:
      - goos: windows
        goarch: arm64
        # Windows ARM64 支持有限，可选择跳过
        # skip: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    name_template: |-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}darwin
      {{- else }}{{ .Os }}{{ end }}-
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    wrap_in_directory: false

    files:
      - LICENSE
      - README.md
      - example-config.yaml
      - GITHUB_WORKFLOW_GUIDE.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: your-github-username
    name: cos-uploader

  # draft: true
  prerelease: false

  name_template: 'Release {{.Version}}'

  body_templated: true

  body: |-
    ## COS File Monitor & Uploader {{.Version}}

    ### Downloads

    Available for:
    - **Linux**: amd64, arm64
    - **macOS**: Intel (amd64), Apple Silicon (arm64)
    - **Windows**: amd64, arm64

    ### Installation

    #### Linux/macOS
    ```bash
    tar -xzf cos-uploader-{{ .Version }}-linux_amd64.tar.gz
    chmod +x cos-uploader
    ./cos-uploader --version
    ```

    #### Windows
    ```powershell
    Expand-Archive cos-uploader-{{ .Version }}-windows_amd64.zip
    cd cos-uploader
    .\cos-uploader.exe --version
    ```

    ### What's Changed

    {{ range .Commits -}}
    * {{ if .Refs }}{{ .Refs }} - {{ end }}{{ .Message }} (@{{ .Author.Name }})
    {{ end -}}

    ### Checksums

    ```
    {{ range .Checksum -}}
    {{ . }}
    {{ end -}}
    ```

    See [README.md](../blob/{{ .Tag }}/README.md) for documentation.
